version: "3"
services:
  web:
    container_name: web
    image: ghcr.io/vim/website_next_generation/web:${TAG:-development}
    environment:
      - CMS_API=http://cms:1337/api
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    ports:
      - 3000:3000
    networks:
      - vim_network

  db:
    container_name: db
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${CMS_DATABASE_NAME}
    volumes:
      - vim-cms-data:/var/lib/mysql
      - ./db/docker-scripts:/docker-entrypoint-initdb.d
    ports:
      - ${DATABASE_PORT}:3306
    networks:
      - vim_network

  cms:
    container_name: strapi
    image: ghcr.io/vim/website_next_generation/cms:${TAG:-development}
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${CMS_DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: false
      URL: ${CMS_URL}
      HOST: ${CMS_HOST}
      PORT: ${CMS_PORT}
      APP_KEYS: ${CMS_APP_KEYS}
      API_TOKEN_SALT: ${CMS_API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${CMS_ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${CMS_TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${CMS_JWT_SECRET}
      STRAPI_DISABLE_UPDATE_NOTIFICATION: ${CMS_DISABLE_UPDATE_NOTIFICATION}
      STRAPI_TELEMETRY_DISABLED: ${CMS_TELEMETRY_DISABLED}
    ports:
      - 1337:1337
    networks:
      - vim_network
    depends_on:
      - db

volumes:
  vim-cms-data:

networks:
  vim_network:
    name: vim_network
    driver: bridge
